package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logging",
    srcs = [
        "logging.cpp",
    ],
    hdrs = [
        "logging.h",
    ],
    deps = [
        "//common:comm",
        "//proto:logging_cc_proto",
    ],
)

