package(default_visibility = ["//visibility:public"])

cc_library(
    name = "xxxdb_kv_client",
    srcs = ["xxxdb_kv_client.cpp"],
    hdrs = ["xxxdb_kv_client.h"],
    deps = [
        "//client:xxxdb_user_client",
        "//proto:kv_server_cc_proto",
    ],
)
