package(default_visibility = ["//visibility:public"])

cc_library(
    name = "txn_memory_db",
    srcs = ["txn_memory_db.cpp"],
    hdrs = ["txn_memory_db.h"],
    deps = [
        "//common:comm",
        "//proto:xxxdb_cc_proto",
    ],
)

